### ISSUE TITLE
Using with new version of RgoogleMaps gives wrong positions 

### ISSUE THREAD

**Issue by daniel-barnett** [iNZightVIT/iNZightMaps#17]
Using iNZightMaps with the RgoogleMaps 1.4.2 seems to put the lat/long coordinates in the wrong place. Downgrading to RgoogleMaps 1.2.0.7 does seem to work (not sure about 1.4.1). It might be something to do with the way that the new version zooms. 

These are the correct positions using the old version (compare to the following lite screenshot):
![maps](https://user-images.githubusercontent.com/16076593/42365784-8e1cc33c-8153-11e8-8549-4f809b33b733.jpg)

This seems to be a problem on the production version of lite too: 
![image](https://user-images.githubusercontent.com/16076593/42365657-36487a8e-8153-11e8-91b7-8907bfd019ba.png)

**Comment by tmelliott** [comment]
Right - I'm pretty sure I fixed this by taking an older version of maps and bumping the version slightly and hosting that on our server - a change in some function or another is breaking the code. I'll do the same thing ASAP.

PS: if you just install from r.docker.stat.auckland.ac.nz, it should work ...

**Comment by daniel-barnett** [comment]
There was actually another thing going on with that too; when I downloaded any version of iNZight and went to the Maps module (old one in the case of the release version), it tried to install the source version of maptools and RgoogleMaps. 

(which is why the problem came up, as I just simply did the usual `install.packages(..., type = "binary")` without specifying the repo)

**Comment by tmelliott** [comment]
This will be redundant now that we're no longer using Google Maps (#27)
