### ISSUE TITLE
Dev version of ggmap still required

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightMaps#44]
Is the dev version of ggmap still required, or safe to fall back on CRAN version (which is at 3.0.0).
https://github.com/iNZightVIT/iNZightMaps/blob/de8d0068533d278c2b5c1cd2f3fab31568700e14/.travis.yml#L17-L18

**Comment by tmelliott** [comment]
@daniel-barnett

**Comment by daniel-barnett** [comment]
I think this should be fine. The git blame is from 2018 and 3.0.0 was released in 2019, and testing it just now with the CRAN version doesn't give me any issues.
